2024-11-20 12:56:17,684 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 68, in setUp
    self.second = Runner(False, 5)
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-20 12:56:17,698 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 68, in setUp
    self.second = Runner(False, 5)
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-20 12:56:17,775 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 68, in setUp
    self.second = Runner(False, 5)
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\ЕПШ\Documents\GitHub\Homework\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-20 12:56:17,776 | INFO | "test_walk" выполнен успешно
